version: '3'
services: 
  mongo: 
    container_name: docker-mongo
    command: [--auth]
    image: mongo:4
    restart: always
    volumes:
      - '../data/db:/data/db'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${PASS}"
  backend:
    container_name: docker-backend
    image: golang:1
    restart: always
    working_dir: /go/src
    build: './backend'
    volumes:
      - './backend/src:/go/src'
      - '/etc/letsencrypt:/etc/letsencrypt'
    command: bash -c "go build main.go && ./main"
    environment:
      - DEVPROD=prod
    ports:
      - '3000:80'
      - '3001:443'
    depends_on: 
      - mongo
  scraper:
    container_name: docker-scraper
    image: node:10
    restart: always
    volumes:
      - './scraper:/usr/src/scraper'
      - './scraper/startup.sh:/tmp/startup.sh'
    command: /bin/sh /tmp/startup.sh
    ports:
      - '3002:3000'
    depends_on: 
      - backend
