version: '3'
services: 
  mongo: 
    container_name: docker-mongo
    image: mongo:4
    restart: always
    volumes:
      - '/usr/src/db:/data/db'
    ports:
      - '27017:27017'
  backend:
    container_name: docker-backend
    image: node:10
    restart: always
    volumes:
      - './backend:/usr/src/backend'
      - './backend/startup.sh:/tmp/startup.sh'
      - '/etc/letsencrypt/live/chalmerskurser.se:/etc/letsencrypt/live/chalmerskurser.se'
    command: /bin/sh /tmp/startup.sh
    ports:
      - '3000:80'
      - '3001:443'
  scraper:
    container_name: docker-scraper
    image: node:10
    restart: always
    volumes:
      - './scraper:/usr/src/scraper'
      - './scraper/startup.sh:/tmp/startup.sh'
    command: /bin/sh /tmp/startup.sh
    ports:
      - '3002:3000'
